config/routes.rb
Rails.application.routes.draw do
  root "orders#index"
  resources :orders
  namespace :orders do
    resources :csv, only: [:show]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
require "csv"
class Order < ApplicationRecord
  has_many :order_items
  accepts_nested_attributes_for :order_items, reject_if: :all_blank, allow_destroy: true

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.price) : 0 }.sum
  end

  def sales_tax
    order_items.collect { |oi| oi.sales_tax_exempt? ? 0 : ((oi.quantity * oi.price * 0.1) * 20).ceil / 20.0 }.sum
  end

  def import_tax
    order_items.collect { |oi| !oi.imported? ? 0 : (oi.quantity * oi.price * 0.05) }.sum.truncate(2)
  end

  def taxes
    sales_tax + import_tax
  end

  def total
    subtotal + taxes
  end

  def csv_output
    CSV.generate do |csv|
      csv << ["Quantity", "Name", "Price"]
      order_items.each do |oi|
        csv << [oi.quantity, oi.name, helpers.number_with_precision(oi.price, precision: 2)]
      end
      csv << [""]
      csv << ["Sales Taxes:", helpers.number_with_precision(sales_tax, precision: 2)]
      csv << ["Total:", helpers.number_with_precision(total, precision: 2)]
    end
  end

  def helpers
    ActionController::Base.helpers
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  validates :quantity, presence: true, numericality: {only_integer: true, greater_than: 0}
  validates :price, presence: true, numericality: {greater_than: 0}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders/csv_controller.rb
class Orders::CsvController < ApplicationController
  before_action :set_order

  def show
    respond_to do |format|
      format.csv { send_data @order.csv_output, filename: "order-#{@order.id}.csv" }
    end
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[show edit update destroy]

  # GET /orders or /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1 or /orders/1.json
  def show
    @order_items = @order.order_items
  end

  # GET /orders/new
  def new
    @order = Order.new
    @order.order_items.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to order_url(@order), notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to order_url(@order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def order_params
    params.require(:order).permit(:subtotal, :tax, :total, order_items_attributes: [:id, :price, :name, :quantity, :imported, :sales_tax_exempt, :_destroy])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taxapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="max-w-3xl mx-auto">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/order_items/_order_item.html.erb
<li class="flex py-6 space-x-6">
  <img src="https://tailwindui.com/img/ecommerce-images/confirmation-page-06-product-01.jpg" alt="Model wearing men&#039;s charcoal basic tee in large." class="flex-none w-24 h-24 bg-gray-100 rounded-md object-center object-cover">
  <div class="flex-auto space-y-1">
    <h3 class="text-gray-900">
      <a href="#"><%= order_item.quantity %> x <%= order_item.name %></a>
    </h3>
  </div>
  <p class="flex-none font-medium text-gray-900"><%= number_to_currency order_item.price %></p>
</li>

app/views/orders/_form.html.erb
<%= form_with(model: order, class: "space-y-8 divide-y") do |form| %>
  <div class="space-y-8 divide-y divide-gray-200">
        <div>
      <div>
        <h3 class="text-lg leading-6 font-medium text-gray-900">
          Order
        </h3>
      </div>

    <% if order.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

        <ul>
          <% order.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <h4>Order Items</h4>
    <div data-controller="nested-form">
      <template data-nested-form-target="template">
        <%= form.fields_for :order_items, OrderItem.new, child_index: 'NEW_RECORD' do |order_item| %>
          <%= render "order_item_fields", form: order_item %>
        <% end %>
      </template>

      <%= form.fields_for :order_items do |order_item| %>
        <%= render "order_item_fields", form: order_item %>
      <% end %>

      <div class="mt-7 mb-3 flex" data-nested-form-target="links">
        <button type="button" data-action="click->nested-form#add_association" class="inline-flex items-center p-1 border border-transparent rounded-full shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
          <!-- Heroicon name: solid/plus-sm -->
          <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M10 5a1 1 0 011 1v3h3a1 1 0 110 2h-3v3a1 1 0 11-2 0v-3H6a1 1 0 110-2h3V6a1 1 0 011-1z" clip-rule="evenodd" />
          </svg>
        </button>
        <p class="ml-3 mt-1 text-gray-600">
        Add Order Item
        </p>
      </div>
    </div>

    <div>
      <%= form.submit class: "inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>

    </div>
  </div>
<% end %>

app/views/orders/_order.html.erb
<dl class="text-sm font-medium text-gray-500 space-y-6 border-t border-gray-200 pt-6">
  <div class="flex justify-between">
    <dt>Subtotal</dt>
    <dd class="text-gray-900">
      <%= number_to_currency(order.subtotal) %>
    </dd>
  </div>

  <div class="flex justify-between">
    <dt>Taxes</dt>
    <dd class="text-gray-900">
      <%= number_to_currency(order.taxes) %>
    </dd>
  </div>

  <div class="flex items-center justify-between border-t border-gray-200 text-gray-900 pt-6">
    <dt class="text-base">Total</dt>
    <dd class="text-base">
      <%= number_to_currency(order.total) %>
    </dd>
  </div>
</dl>

app/views/orders/_order_item_fields.html.erb
<%= content_tag :div, class: "nested-fields mb-3 p-4 space-y-3 border-2 border-gray-300 rounded", data: { new_record: form.object.new_record? } do %>
  <div class="grid grid-cols-5 space-x-1">
    <div class="form-group col-span-1">
      <%= form.label :quantity, class: "block text-sm font-medium text-gray-700" %>
      <%= form.select(:quantity, ((1..50).map {|i| [i,i] }), { default: 1 }, { class: "mt-1 block w-full pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md" })%>
    </div>
    <div class="form-group col-span-2 mt-1">
      <%= form.label :name, class: "block text-sm font-medium text-gray-700" %>
      <%= form.text_field :name, class: 'shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md' %>
    </div>
    <div class="form-group col-span-2">
      <div>
        <%= form.label :price, class: "block text-sm font-medium text-gray-700" %>
        <div class="mt-1 relative rounded-md shadow-sm">
          <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
            <span class="text-gray-500 sm:text-sm">
              $
            </span>
          </div>
          <%= form.number_field :price, in: 0.01..100.0, step: 0.01, placeholder: 0.00, class: "focus:ring-indigo-500 focus:border-indigo-500 block w-full pl-7 pr-12 sm:text-sm border-gray-300 rounded-md" %>
          <div class="absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none">
            <span class="text-gray-500 sm:text-sm" id="price-currency">
              USD
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= form.check_box :sales_tax_exempt, class: "h-4 w-4 text-indigo-500 focus:ring-indigo-500 border-gray-300 rounded" %>
    <%= form.label :sales_tax_exempt %>
  </div>
  <div class="form-group">
    <%= form.check_box :imported, class: "h-4 w-4 text-indigo-500 focus:ring-indigo-500 border-gray-300 rounded" %>
    <%= form.label :imported %>
  </div>
    <button type="button" data-action="click->nested-form#remove_association" class="inline-flex items-center px-3 py-2 border border-transparent shadow-sm text-sm leading-4 font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
      Remove Order Item
      <svg class="ml-2 -mr-0.5 h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
        <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
      </svg>
    </button>
  <%= form.hidden_field :_destroy %>
<% end %>

app/views/orders/edit.html.erb
<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Show this order", @order %> |
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Orders</h1>

<div id="orders">
  <% @orders.each do |order| %>
    <%= render order %>
    <p>
      <%= link_to "Goto Order", order, class: "inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
    </p>
  <% end %>
</div>

<%= link_to "Create new order", new_order_path, class: "mt-2 inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/show.html.erb
<p style="color: green"><%= notice %></p>


<div>
  <%= link_to "Back to orders", orders_path %>
  <%= link_to "Edit Order", edit_order_path(@order) %>

  <%= button_to "Destroy this order", @order, method: :delete %>
</div>

<main class="relative lg:min-h-full">
  <div class="h-80 overflow-hidden lg:absolute lg:w-1/2 lg:h-full lg:pr-4 xl:pr-12">
    <img src="https://tailwindui.com/img/ecommerce-images/confirmation-page-06-hero.jpg" alt="TODO" class="h-full w-full object-center object-cover">
  </div>

  <div>
    <div class="max-w-2xl mx-auto py-16 px-4 sm:px-6 sm:py-24 lg:max-w-7xl lg:px-8 lg:py-32 lg:grid lg:grid-cols-2 lg:gap-x-8 xl:gap-x-24">
      <div class="lg:col-start-2">
        <h1 class="text-sm font-medium text-indigo-600">Order Summary</h1>
        <p class="mt-2 text-4xl font-extrabold tracking-tight text-gray-900 sm:text-5xl">Here's the summary</p>

        <ul role="list" class="mt-6 text-sm font-medium text-gray-500 border-t border-gray-200 divide-y divide-gray-200">
          <%= render @order_items %>
        </ul>

        <%= render @order %>

        <div class="mt-16 border-t border-gray-200 py-6 text-right space-x-3">
          <%= link_to "Edit Order", edit_order_path(@order), class: "text-sm font-medium text-indigo-600 hover:text-indigo-500" %>
          <%= link_to "Export CSV", orders_csv_path(@order, format: :csv), class: "text-sm font-medium text-indigo-600 hover:text-indigo-500" %>
        </div>
      </div>
    </div>
  </div>
</main>